### ISSUE TITLE
Non-ascii characters (ä, ö, ...) in `ref` keys problems

### ISSUE THREAD

**Issue by tuurep** [papis/papis#1004]
From https://github.com/papis/papis/issues/1002#issuecomment-2817809874, where I thought this was the same issue as something else:

>> Hey, I remember having a similar problem querying a string with the >> Finnish `ä` and `ö` characters.
>>
>> Looked at it again, `title` can be queried with `ä` and `ö`, but not >> `ref` (i.e. the citation key).
>>
>> Maybe it's something about UTF-8 support?
> 
> This sounds unrelated. Might be because we're generally "slugifying" references (since standard BibTeX doesn't support Unicode to my knowledge?). Can you open a separate issue with some example that doesn't work? (i.e. an `info.yml` file or something)

Here's an example with the primary author name *Käkönen*:

`$ papis add --from doi 10.1002/cncr.11132`

`info.yaml` produced with the enormous `citations` field removed:

```yaml
author: K�k�nen, Sanna-Maria and Mundy, Gregory R.
author_list:
- affiliation: []
  family: K�k�nen
  given: Sanna-Maria
- affiliation: []
  family: Mundy
  given: Gregory R.
doc_url: https://onlinelibrary.wiley.com/doi/full/10.1002/cncr.11132
doi: 10.1002/cncr.11132
files: []
issue: S3
journal: Cancer
language: en
month: 2
pages: 834--839
papis_id: c9266fc224159175277144cc36eb9111
publisher: Wiley
ref: kknen2003
time-added: 2025-04-21-20:33:00
title: Mechanisms of osteolytic bone metastases in breast carcinoma
type: article
url: https://doi.org/10.1002/cncr.11132
volume: '97'
year: 2003
```

Notice it has those � characters in the author fields, this is something I saw for the first time with this example.

My `ref` is generated with this jinja2 template:

```
ref-format = {%% if doc["author_list"] %%}{{ doc["author_list"][0]["family"].lower() }}{%% else %%}{{ doc["publisher"].lower() }}{%% endif %%}{{ doc["year"] }}
```

(TL;DR: `<1st author family><year>`)

Fixing the �s by hand we get this "correct" info.yaml:

```yaml
author: Käkönen, Sanna-Maria and Mundy, Gregory R.
author_list:
- affiliation: []
  family: Käkönen
  given: Sanna-Maria
- affiliation: []
  family: Mundy
  given: Gregory R.
doc_url: https://onlinelibrary.wiley.com/doi/full/10.1002/cncr.11132
doi: 10.1002/cncr.11132
files: []
issue: S3
journal: Cancer
language: en
month: 2
pages: 834--839
papis_id: c9266fc224159175277144cc36eb9111
publisher: Wiley
ref: käkönen2003
time-added: 2025-04-21-20:33:00
title: Mechanisms of osteolytic bone metastases in breast carcinoma
type: article
url: https://doi.org/10.1002/cncr.11132
volume: '97'
year: 2003
```

And this is the primary issue, document can't be queried with

`$ papis edit käkönen2003`

But this works:

`$ papis edit nen2003`

I made sure to check that I'm able to use an actual bib citekey like `käkönen2003` in a tex document, since I wasn't sure about this:

> (since standard BibTeX doesn't support Unicode to my knowledge?)

Maybe specific to my setup.
