### ISSUE TITLE
More flexible `ref-format`

### ISSUE THREAD

**Issue by avonmoll** [papis/papis#114]
`Author1990` is a decent ref-format, but what if we want something a little more specific, e.g. lowercase first author surname, followed by year, followed by lowercase first word of title (minus [stopwords](https://www.geeksforgeeks.org/removing-stop-words-nltk-python/))?

```YAML
author_list:
  - given_name: First
  - surname: Last
title: A very good paper
year: 1990
```

becomes `last1990very`.

I messed around a bit with the string formatting and it looks like only accession is allowed within replacement strings (i.e. not other string operations like `lower` or `split`).
