### ISSUE TITLE
Imported metadata has errors.

### ISSUE THREAD

**Issue by BonaBeavis** [papis/papis#143]
Importing a paper with papis, version 0.8.2 and:

`papis add --from-doi 10.1145/3184558.3186235`

gives following metadata:

```yml
author: Champin, Pierre-Antoine and Gandon, Fabien and Gandon, Fabien and Lalmas,
  Mounia and Ipeirotis, Panagiotis G. and Bühmann, Lorenz and Lehmann, Jens and Westphal,
  Patrick and Bin, Simon
author_list:
- given_name: Pierre-Antoine
  surname: Champin
- given_name: Fabien
  surname: Gandon
- given_name: Fabien
  surname: Gandon
- given_name: Mounia
  surname: Lalmas
- given_name: Panagiotis G.
  surname: Ipeirotis
- given_name: Lorenz
  surname: Bühmann
- given_name: Jens
  surname: Lehmann
- given_name: Patrick
  surname: Westphal
- given_name: Simon
  surname: Bin
booktitle: Companion of the The Web Conference 2018 on The Web Conference 2018  -
  WWW '18
citations:
- doi: 10.1007/978-3-319-13704-9_4
- doi: 10.1007/978-3-642-33876-2_8
- doi: 10.1007/978-3-642-41335-3_3
- doi: 10.1016/j.websem.2016.06.001
- doi: 10.1007/s10994-008-5079-1
- doi: 10.4018/978-1-60960-593-3.ch005
- doi: 10.1109/ISDA.2011.6121843
- doi: 10.1145/2566486.2568002
- doi: 10.1007/978-3-540-73499-4_66
- doi: 10.1016/j.websem.2011.01.001
- doi: 10.1007/978-3-642-17749-1_12
- doi: 10.1007/978-3-642-21034-1_5
- doi: 10.1007/s10994-011-5259-2
- doi: 10.1007/3-540-62927-0
- doi: 10.1007/978-3-642-32689-9_25
doi: 10.1145/3184558.3186235
files: []
first_page: '467'
last_page: '471'
month: null
pages: 467--471
ref: 10.1145/3184558.3186235
title: DL-Learner Structured Machine Learning on Semantic Web Data
type: inproceedings
year: '2018'
```

There are three issues:
1. Author is wrong.
2. One author is listed two times.
3. Booktitle is not a valid multiline yaml string
