### ISSUE TITLE
The exported BibTeX files do not retain the correct file locations for the corresponding PDF files.

### ISSUE THREAD

**Issue by Enrico68** [papis/papis#721]
**Issue Description**
When exporting to BibTeX format (`papis export --all -f bibtex -o libreria.bib`), the exported file does not maintain the correct file locations for corresponding PDF files. 

**Environment**
- papis version (`$ papis --version` or commit number): `papis, version 0.13`

**Steps to Reproduce**
1. Run the following command: 
```
papis export --all -f bibtex -o libreria.bib
```
2. The exported BibTeX entry will look like this:
```
@article{ExtracorporealJones2015,
  author = {Jones, Daryl and Hilton, Andrew and Bellomo, Rinaldo},
  file = {/Users/enricopirani/Zotero/storage/2LTJSJEG/2015.Bellomo\_2.pdf},
  issn = {1441-2772},
  journal = {Critical care and resuscitation : journal of the Australasian Academy of Critical Care Medicine Critical Care Resusc J Australas Acad Critical Care Medicine},
  note = {file://localhost/Users/enricopirani/Library/Mobile\textbackslash{}\%20Documents/iCloud\lbrace{}\textbackslash{}textasciitilde\rbrace{}com\lbrace{}\textbackslash{}textasciitilde\rbrace{}sonnysoftware\lbrace{}\textbackslash{}textasciitilde\rbrace{}bot/Documents/2015.Bellomo\textbackslash{}\_2.pdf},
  number = {1},
  pages = {3--5},
  title = {Extracorporeal Membrane Oxygenation for Inhospital Cardiac Arrests: The Rise of the Machines.},
  volume = {17},
  year = {2015},
}
```

**Expected Behavior**
The file location should point to the correct location of the corresponding PDF file.

**Additional Information**
The file location in the exported BibTeX file is pointing to the old location where it was located before. This problem seems to occur only when importing from Zotero.
```

**Comment by alexfikl** [comment]
This might be because `papis-zotero` only links the files into your library, see
https://github.com/papis/papis-zotero/blob/e211e9d50524048b7f9f8e7a766842ba05866638/papis_zotero/bibtex.py#L58-L60

What does your library look like for that document, i.e.
* What does the `info.yaml` file contain in the `files` entry?
* Is that file in the same folder and not a symlink?

**Comment by Enrico68** [comment]
> This might be because `papis-zotero` only links the files into your library, see https://github.com/papis/papis-zotero/blob/e211e9d50524048b7f9f8e7a766842ba05866638/papis_zotero/bibtex.py#L58-L60
> 
> What does your library look like for that document, i.e.
> 
>     * What does the `info.yaml` file contain in the `files` entry?

```
author: Russell, Stuart J. and Norvig, Peter and RUSSELL, Stuart and Russell, Stuart
  and ), [ MEI ] NUO WEI GE ( Peter Norvig ) [ MEI ] LUO SU ( Stuart J.Russell
author_list:
- family: Russell
  given: Stuart J.
- family: Norvig
  given: Peter
- family: RUSSELL
  given: Stuart
- family: Russell
  given: Stuart
- family: )
  given: '[ MEI ] NUO WEI GE ( Peter Norvig ) [ MEI ] LUO SU ( Stuart J.Russell'
files:
- stuart-j.-russell-peter-norvig-artificial-intelligence-a-modern-approach-global-edition-pearson-2021.pdf
isbn: '9781292401133'
isbn-13: '9781292401133'
language: ''
papis_id: 98a5d2bcd3d37e2ff2a918bbafd433d1
publisher: Pearson Publishing
ref: ArtificialInteRussel2021
time-added: 2023-12-31-14:28:14
title: Artificial Intelligence - A Modern Approach
year: '2021'
````

>     * Is that file in the same folder and not a symlink?

the file is in the same folder. 
The problem is just a minor one as it would be useful to have the exported papers togheter with the right files link
