### ISSUE TITLE
Feature request: Use CWD as default if it is configured as a library

### ISSUE THREAD

**Issue by hseg** [papis/papis#952]
* papis version (`$ papis --version` or commit number): 340e7f61

# how to reproduce the issue

With the following `papis/config`:
```toml
[papers]
dir = ~/Documents/papers

[settings]
default-library = papers

[self-improvement]
dir = /home/gesh/notes/self-improvement
opentool = xdg-open
editor = vim
use-git = True
notes-name = notes.md
database-backend = papis
bibtex-unicode = True
ref-format = {doc[title]:.15} {doc[author]:.6} {doc[year]}
multiple-authors-format = {au[family]}, {au[given]}
citations-file-name = citations.yaml
```

I get the following output:
```
$ pwd
/home/gesh/notes/self-improvement
$ papis --log INFO list
[ERROR] commands.default: Library 'papers' does not have any folders attached to it. Please create and add the required paths to the configuration file.
[WARNING] commands.list: No documents retrieved
$ papis --log INFO -l self-improvement list
[WARNING] commands.list: No documents retrieved
```

i.e. for non-default libraries, I always need to specify the library.

This is very inconvenient -- I'm used to eg the git model, where despite `-C` allowing you to operate on a repository that's not CWD, the default presumption is that CWD is expected to be inside a repository. I'm willing to pay the price of starting my editing sessions within the library, but needing to remember to pass `-l` on each command gets tiring very fast.

Recommendation: If CWD is inside one of the library directories, use that library by default. Otherwise, fall back to `default-library`. (Incidentally, this can enable workflows where one has no default library, which would fit this model even better)
